#!/usr/bin/env bash

PROTOBOX_CONFIG=".protobox"
# Get user data
if [ -f $PROTOBOX_CONFIG ]; then
  echo "protobox pre-configured"
  source $PROTOBOX_CONFIG
else
  echo "Configuring protobox"
  read -e -p "Project name [protobox]:" PROTOBOX_NAME
  PROTOBOX_NAME=${PROTOBOX_NAME:-protobox}
  read -e -p "Vagrant box [ubuntu/trusty64]:" PROTOBOX_BOX
  PROTOBOX_BOX=${PROTOBOX_BOX:-"ubuntu/trusty64"}
  if [ "$PROTOBOX_BOX" == "protobox-laravel" ]; then
    PROTOBOX_FRMW="laravel"
  else
    read -e -p "Framework slim/laravel/none [slim]:" PROTOBOX_FRMW
    PROTOBOX_FRMW=${PROTOBOX_FRMW:-slim}
  fi
  read -s -p "Password [badedyr19]:" PROTOBOX_PASS
  echo
  PROTOBOX_PASS=${PROTOBOX_PASS:-badedyr19}
  read -e -p "IP 192.168.xx.xx [80.80]:" PROTOBOX_IP
  PROTOBOX_IP=${PROTOBOX_IP:-80.80}
  read -e -p "Git repo (optional):" PROTOBOX_GIT
fi

# sed -i implementation since `-i` is not supported on Mac OSX
sedi() {
  TMP_FILE=`mktemp /tmp/$3.XXXXXXXXXX`
  sed -e "s~$1~$2~" $3 > $TMP_FILE
  mv $TMP_FILE $3
}

# Prepares Vagrantfile + bootstrap.sh
if [ ! -f Vagrantfile ]; then
  cp _templates/Vagrantfile Vagrantfile
  if [ -f extra.sh ]; then
    cat _templates/bootstrap.sh extra.sh >> bootstrap.sh
    mv extra.sh .extra.sh-backup
  else
    cp _templates/bootstrap.sh bootstrap.sh
  fi
fi

sedi "_PROTOBOX_IP" "${PROTOBOX_IP}" Vagrantfile
sedi "_PROTOBOX_BOX" "${PROTOBOX_BOX}" Vagrantfile
sedi "_PROTOBOX_NAME" "${PROTOBOX_NAME}" Vagrantfile
sedi "_PROTOBOX_NAME" "${PROTOBOX_NAME}" bootstrap.sh
sedi "_PROTOBOX_PASS" "${PROTOBOX_PASS}" bootstrap.sh
sedi "_PROTOBOX_FRMW" "${PROTOBOX_FRMW}" bootstrap.sh
#
# # Update git
# git remote rm origin &> /dev/null
# git add Vagrantfile bootstrap.sh &> /dev/null
# git rm install.sh _templates/Vagrantfile _templates/bootstrap.sh &> /dev/null
# git commit -m"Configured vagrant box and removed install files"
# if [ ! -z "$PROTOBOX_GIT" ]; then
#   git remote add -m master origin "$PROTOBOX_GIT" &> /dev/null
#   git push -u origin --all
# fi

_CONFIG=$(cat <<EOT
# Auto-generated by install.sh
PROTOBOX_NAME="$PROTOBOX_NAME"
PROTOBOX_BOX="$PROTOBOX_BOX"
PROTOBOX_FRMW="$PROTOBOX_FRMW"
PROTOBOX_PASS="$PROTOBOX_PASS"
PROTOBOX_IP="$PROTOBOX_IP"
PROTOBOX_GIT="$PROTOBOX_GIT"
EOT)
echo "$_CONFIG" > "$PROTOBOX_CONFIG"

echo "Now run: vagrant up"