# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  # Create a private network, which allows host-only access to the machine using a specific IP.
  config.vm.network "private_network", ip: "192.168._PROTOBOX_IP"

  # Share an additional folder to the guest VM. The first argument is the path on the host to the actual folder.
  # The second argument is the path on the guest to mount the folder.
  config.vm.synced_folder "./", "/srv/www"

  # VirtualBox setup
  config.vm.provider "virtualbox" do |v|
    
    v.name = "_PROTOBOX_NAME-box"
    
    # Don't boot with headless mode
    # v.gui = true

    # Use VBoxManage to customize the VM. For example to change memory:
    v.memory = 2048
    # v.customize ["modifyvm", :id, "--memory", "2048"]
    v.cpus = 2
    
    # v.customize ["modifyvm", :id, "--pae", "on"]
    v.customize ["modifyvm", :id, "--usb", "off"]
    v.customize ["modifyvm", :id, "--usbehci", "off"]
  end

  config.vm.provision :shell, path: "bootstrap.sh"

end
